# package-id:dependency-id,dependency-id
kmod-git:
libdrm-git:
libinput-git:
seatd-git:
polkit-git:glib2-git
dbus-broker-git:
wayland-git:
glib2-git:
vulkan-headers-git:
vulkan-icd-loader-git:vulkan-headers-git
libva-git:libdrm-git
cairo-git:
pango-git:cairo-git
libadwaita-git:gtk4-git,pango-git
gtk3-git:pango-git,cairo-git
gtk4-git:pango-git,cairo-git,glib2-git
xorg-xwayland-git:libdrm-git
qt5-base-git:gtk3-git
qt6-base-git:
pyside6-git:qt6-base-git
libdex-git:glib2-git,liburing-git
xdg-desktop-portal-git:libdex-git
xdg-desktop-portal-gtk-git:gtk3-git
xdg-desktop-portal-gnome-git:xdg-desktop-portal-git,xdg-desktop-portal-gtk-git
xwayland-satellite-git:
jemalloc-git:
liburing-git:
lz4-git:
mimalloc-git:
pixman-git:
xz-git:
zlib-ng-compat-git:
zlib-ng-git:
zstd-git:
easyeffects-git:qt6-graphs
libunwind-git:
ninja-git:
hsa-rocr:rocm-core,rocm-llvm
hip-runtime:rocm-core,rocm-llvm,hsa-rocr
util-linux:
gcc-snapshot:
llvm-git:
spirv-llvm-translator-git:llvm-git
mold-git:
rust-git:llvm-git
cmake-git:
doxygen-git:cmake-git
meson-git:ninja-git
rocm-core:
rocm-llvm:rocm-core
libclc-git:spirv-llvm-translator-git
mesa-git:rust-git,libclc-git,llvm-git
niri-spicy-git:rust-git
noctalia-git:
vscodium-insiders-git:
autofdo-git:
bpftune-git:
scx-scheds-git:rust-git
scx-tools-git:scx-scheds-git,rust-git
libisl-git:
dbus:
linux-api-headers:
linux-firmware:
linux-tools:
fish:rust-git
zram-generator:rust-git
pipewire:dbus
udisks2:dbus,polkit-git,glib2-git
wireplumber:pipewire,glib2-git
xcb-imdkit-git:
fcitx5-git:xcb-imdkit-git,cairo-git,pango-git,wayland-git,glib2-git
fcitx5-lua-git:fcitx5-git
libime-git:fcitx5-git
fcitx5-qt-git:fcitx5-git,qt6-base-git,qt5-base-git
fcitx5-gtk-git:fcitx5-git,gtk3-git,gtk4-git,glib2-git
fcitx5-chinese-addons-git:libime-git,fcitx5-qt-git,fcitx5-git
qt6-shadertools:qt6-base-git
qt6-languageserver:qt6-base-git
qt6-svg:qt6-base-git
qt6-serialport:qt6-base-git
qt6-declarative:qt6-base-git,qt6-shadertools,qt6-svg,qt6-languageserver
qt6-quick3d:qt6-base-git,qt6-declarative,qt6-shadertools
qt6-tools:qt6-base-git,qt6-declarative
qt6-webchannel:qt6-base-git,qt6-declarative
qt6-positioning:qt6-base-git,qt6-declarative,qt6-serialport
qt6-multimedia:qt6-base-git,qt6-declarative,qt6-shadertools,qt6-quick3d
qt6-speech:qt6-base-git,qt6-declarative
qt6-graphs:qt6-base-git,qt6-declarative,qt6-quick3d
qt6ct:qt6-base-git,qt6-tools
qt5-declarative:qt5-base-git
qt5-multimedia:qt5-base-git,qt5-declarative
qt5-tools:qt5-base-git,qt5-declarative
qt5-speech:qt5-base-git
qt5-svg:qt5-base-git
qt5-webchannel:qt5-base-git
qt5-x11extras:qt5-base-git
qt5ct:qt5-base-git,qt5-tools
rust-bindgen-git:rust-git
flatpak-git:glib2-git,polkit-git
babl-git:glib2-git
gegl-git:babl-git
gimp-git:gegl-git,babl-git
krita-git:qt6-base-git,qt6-svg,qt6-tools
openssl:
openssh:openssl
openvpn:openssl
git-git:openssl
networkmanager:glib2-git,polkit-git
networkmanager-openvpn:networkmanager
upower:glib2-git,polkit-git
libreoffice-fresh:openssl
ccache:
systemd:linux-api-headers,util-linux
dbus-broker:systemd
openshadinglanguage:llvm-git,qt6-base-git
blender-git:openshadinglanguage
